---
name: Slack Notifications
description: "Slack Notification for pipeline updates"
inputs: 
    channel-id: 
        description: "ID of channel to sent notification to."
        required: true
    pipeline-name:
        description: "Name of pipeline for slack message"
        required: true

 runs:
    using: "composite"
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: ${{ inputs.channel-id }}
        slack-message: "${{ inputs.pipeline-name }} build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}